// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sspupghymzfikfemusdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcHVwZ2h5bXpmaWtmZW11c2RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Mjk4NDEsImV4cCI6MjA1ODIwNTg0MX0.9ulwiSc32kkNJKWKtJWubbUistc4uyQG1uTUdCXSvuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);